apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: sock-shop
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/microservices-demo/microservices-demo
  ref:
    branch: master
