apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sock-shop
  namespace: sock-shop
spec:
  interval: 4m
  chart:
    spec:
      chart: ./deploy/kubernetes/helm-chart/
      sourceRef:
        kind: GitRepository
        name: sock-shop
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1
